name: analyzer_to_html
description: Export Flutter or Dart Analyzer reports to be HTML.
version: 1.0.0
homepage: https://github.com/ybbond/analyzer_to_html

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
dependencies: 
  args: ^2.2.0
